CREATE TABLE transfer (
  id                UUID PRIMARY KEY,
  source_account_id UUID NOT NULL REFERENCES account(id),
  target_account_id UUID NOT NULL REFERENCES account(id),
  amount            NUMERIC(19,4) NOT NULL,
  currency          VARCHAR(3) NOT NULL,
  kind              VARCHAR(16) NOT NULL,
  reference         VARCHAR(140),
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT transfer_amount_positive   CHECK (amount > 0),
  CONSTRAINT transfer_distinct_accounts CHECK (source_account_id <> target_account_id),
  CONSTRAINT transfer_kind_valid        CHECK (kind IN ('TRANSFER','DEPOSIT','WITHDRAWAL'))
);

CREATE TABLE ledger_entry (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id   UUID NOT NULL REFERENCES transfer(id),
  account_id    UUID NOT NULL REFERENCES account(id),
  direction     VARCHAR(6) NOT NULL,
  amount        NUMERIC(19,4) NOT NULL,
  currency      VARCHAR(3) NOT NULL,
  balance_after NUMERIC(19,4) NOT NULL,
  created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ledger_direction_valid CHECK (direction IN ('DEBIT','CREDIT')),
  CONSTRAINT ledger_sign_matches
    CHECK ((direction = 'DEBIT' AND amount < 0) OR (direction = 'CREDIT' AND amount > 0)),
  CONSTRAINT ledger_one_entry_per_account UNIQUE (transfer_id, account_id)
);
CREATE INDEX idx_ledger_account_history ON ledger_entry (account_id, id DESC);
