CREATE TABLE idempotency_record (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id       VARCHAR(64)  NOT NULL,
  idempotency_key VARCHAR(255) NOT NULL,
  -- VARCHAR, not CHAR: CHAR(n) with an explicit columnDefinition
  -- validates fine on H2 but fails Hibernate's Postgres-dialect schema
  -- check (see F06). SHA-256 hex is always exactly 64 characters either
  -- way, so this costs nothing functionally.
  fingerprint     VARCHAR(64)  NOT NULL,
  transfer_id     UUID NOT NULL REFERENCES transfer(id),
  response_status INT  NOT NULL,
  response_body   TEXT NOT NULL,
  created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT idempotency_key_unique UNIQUE (client_id, idempotency_key)
);
